Trait {
	#name : #TWDCVREventHandler,
	#category : #'WodenEngine-Core-VR'
}

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRButtonPressedEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRButtonReleasedEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRButtonTouchEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRButtonUntouchEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogCancelEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogModeSwitch1Event: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogModeSwitch2Event: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogMoveEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogPressedEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogReleasedEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogTouchEvent: event [
]

{ #category : #'as yet unclassified' }
TWDCVREventHandler >> onVRDualAnalogUntouchEvent: event [
]
