Class {
	#name : #WDAEventVisitor,
	#superclass : #OSWindowEventVisitor,
	#category : #'WodenEngine-Core-Application-Events'
}

{ #category : #visiting }
WDAEventVisitor >> visitClickEvent: event [
]

{ #category : #visiting }
WDAEventVisitor >> visitDoubleClickEvent: event [
]

{ #category : #visiting }
WDAEventVisitor >> visitMouseDragEndEvent: event [
]

{ #category : #visiting }
WDAEventVisitor >> visitMouseDragEvent: event [
]

{ #category : #visiting }
WDAEventVisitor >> visitMouseDragStartEvent: event [
]
