Class {
	#name : #WDCSpatialSubdivisionDataStructureSimpleElement,
	#superclass : #Object,
	#traits : 'TWDCSpatialSubdivisionDataStructureElement',
	#classTraits : 'TWDCSpatialSubdivisionDataStructureElement classTrait',
	#instVars : [
		'value'
	],
	#category : #'WodenEngine-Core-DataStructures'
}

{ #category : #'as yet unclassified' }
WDCSpatialSubdivisionDataStructureSimpleElement >> spatialElementValue [
	^ value
]

{ #category : #accessing }
WDCSpatialSubdivisionDataStructureSimpleElement >> value [
	^ value
]

{ #category : #accessing }
WDCSpatialSubdivisionDataStructureSimpleElement >> value: anObject [
	value := anObject
]
