Class {
	#name : #WDCVREyeViewportParameters,
	#superclass : #Object,
	#instVars : [
		'outside',
		'inner',
		'top',
		'bottom',
		'eyeX',
		'eyeY'
	],
	#category : 'WodenEngine-Core-VR'
}

{ #category : #accessing }
WDCVREyeViewportParameters >> bottom [
	^ bottom
]

{ #category : #accessing }
WDCVREyeViewportParameters >> bottom: anObject [
	bottom := anObject
]

{ #category : #accessing }
WDCVREyeViewportParameters >> eyeX [
	^ eyeX
]

{ #category : #accessing }
WDCVREyeViewportParameters >> eyeX: anObject [
	eyeX := anObject
]

{ #category : #accessing }
WDCVREyeViewportParameters >> eyeY [
	^ eyeY
]

{ #category : #accessing }
WDCVREyeViewportParameters >> eyeY: anObject [
	eyeY := anObject
]

{ #category : #accessing }
WDCVREyeViewportParameters >> inner [
	^ inner
]

{ #category : #accessing }
WDCVREyeViewportParameters >> inner: anObject [
	inner := anObject
]

{ #category : #accessing }
WDCVREyeViewportParameters >> outside [
	^ outside
]

{ #category : #accessing }
WDCVREyeViewportParameters >> outside: anObject [
	outside := anObject
]

{ #category : #accessing }
WDCVREyeViewportParameters >> top [
	^ top
]

{ #category : #accessing }
WDCVREyeViewportParameters >> top: anObject [
	top := anObject
]
