Class {
	#name : #WDESKinematicPhysicsBehavior,
	#superclass : #WDESBehaviorComponent,
	#category : #'WodenEngine-EntitySystem-Behaviors'
}

{ #category : #'as yet unclassified' }
WDESKinematicPhysicsBehavior >> currentDriver: aDriver [
]

{ #category : #simulation }
WDESKinematicPhysicsBehavior >> prePhysicsTick: delta [
	"This is the place for changing the object linear velocity, angular velocity, etc"
]
