initialize
initialize
"
	self initialize
"
	super initialize.

	agpu_cstring := #'char*'.
	agpu_string := #'char*'.
	agpu_color4f := AGPUColor4f.
	agpu_field_type := #int.
	agpu_buffer_usage_type := #int.
	agpu_mapping_access := #int.
	agpu_texture_address_mode := #int.
	agpu_float := #'float'.
	agpu_buffer_description := AGPUBufferDescription.
	agpu_shader_signature := #'void*'.
	agpu_shader := #'void*'.
	agpu_compare_function := #int.
	agpu_size := #'size_t'.
	agpu_device_open_info := AGPUDeviceOpenInfo.
	agpu_double := #'double'.
	agpu_filter := #int.
	agpu_vertex_attrib_description := AGPUVertexAttribDescription.
	agpu_framebuffer := #'void*'.
	agpu_swap_chain_create_info := AGPUSwapChainCreateInfo.
	agpu_sbyte := #'char'.
	agpu_shader_language := #int.
	agpu_primitive_type := #int.
	agpu_command_list := #'void*'.
	agpu_cstring_buffer := #'char*'.
	agpu_vertex_binding := #'void*'.
	agpu_shader_binding_type := #int.
	agpu_bool := #'bool'.
	agpu_primitive_topology := #int.
	agpu_pipeline_builder := #'void*'.
	agpu_platform := #'void*'.
	agpu_shader_signature_builder := #'void*'.
	agpu_texture_format := #int.
	agpu_byte := #'uchar'.
	agpu_bitfield := #'uint'.
	agpu_buffer := #'void*'.
	agpu_texture := #'void*'.
	agpu_pointer := #'void*'.
	agpu_int := #'int'.
	agpu_string_length := #'int'.
	agpu_vertex_layout := #'void*'.
	agpu_draw_elements_command := AGPUDrawElementsCommand.
	agpu_sampler_description := AGPUSamplerDescription.
	agpu_buffer_mapping_flags := #int.
	agpu_device := #'void*'.
	agpu_texture_flags := #int.
	agpu_stencil_operation := #int.
	agpu_command_queue := #'void*'.
	agpu_string_buffer := #'char*'.
	agpu_shader_resource_binding := #'void*'.
	agpu_enum := #'int'.
	agpu_command_allocator := #'void*'.
	agpu_texture_description := AGPUTextureDescription.
	agpu_swap_chain := #'void*'.
	agpu_shader_type := #int.
	agpu_pipeline_state := #'void*'.
	agpu_error := #int.
	agpu_uint := #'uint'.
	agpu_fence := #'void*'.
	agpu_short := #'short'.
	agpu_buffer_binding_type := #int.
	agpu_render_buffer_bit := #int.
	agpu_texture_type := #int.
	agpu_ushort := #'ushort'.
