Class {
	#name : #WDELevelElement3DDimensionalityMode,
	#superclass : #WDELevelElementDimensionalityMode,
	#category : #'WodenEngine-Editor-Model-Level'
}

{ #category : #accessing }
WDELevelElement3DDimensionalityMode >> dimensionalityMode [
	^ '3D'
]

{ #category : #testing }
WDELevelElement3DDimensionalityMode >> is3D [
	^ true
]

{ #category : #accessing }
WDELevelElement3DDimensionalityMode >> name [
	^ '3D'
]
