comparing
= other
	^ self class = other class and:
		[ (m11 = other m11) and:
		[ (m12 = other m12) and:
		[ (m13 = other m13) and:
		[ (m14 = other m14) and:
		
		[ (m21 = other m21) and:
		[ (m22 = other m22) and:
		[ (m23 = other m23) and:
		[ (m24 = other m24) and:

		[ (m31 = other m31) and:
		[ (m32 = other m32) and:
		[ (m33 = other m33) and:
		[ (m34 = other m34) and:

		[ (m41 = other m41) and:
		[ (m42 = other m42) and:
		[ (m43 = other m43) and:
		[ (m44 = other m44) ]]]]]]]]]]]]]]]]
