Class {
	#name : #WDPhyCollisionMeshAccessor,
	#superclass : #Object,
	#instVars : [
		'vertexBufferData',
		'vertexBufferOffset',
		'vertexBufferStride',
		'vertexCount',
		'indexBufferData',
		'indexBufferOffset',
		'indexBufferStride',
		'indexCount',
		'transform'
	],
	#category : #'WodenEngine-Physics-Interface'
}

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferData [
	^ indexBufferData
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferData: anObject [
	indexBufferData := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferOffset [
	^ indexBufferOffset
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferOffset: anObject [
	indexBufferOffset := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferStride [
	^ indexBufferStride
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexBufferStride: anObject [
	indexBufferStride := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexCount [
	^ indexCount
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> indexCount: anObject [
	indexCount := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> transform [
	^ transform
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> transform: anObject [
	transform := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferData [
	^ vertexBufferData
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferData: anObject [
	vertexBufferData := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferOffset [
	^ vertexBufferOffset
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferOffset: anObject [
	vertexBufferOffset := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferStride [
	^ vertexBufferStride
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexBufferStride: anObject [
	vertexBufferStride := anObject
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexCount [
	^ vertexCount
]

{ #category : #accessing }
WDPhyCollisionMeshAccessor >> vertexCount: anObject [
	vertexCount := anObject
]
