arithmetic
- other
	<argument: #other type: #(SelfType object)>
	^ self class new
		m11: m11 - other m11; m12: m12 - other m12; m13: m13 - other m13; m14: m14 - other m14;
		m21: m21 - other m21; m22: m22 - other m22; m23: m23 - other m23; m24: m24 - other m24;
		m31: m31 - other m31; m32: m32 - other m32; m33: m33 - other m33; m34: m34 - other m34;
		m41: m41 - other m41; m42: m42 - other m42; m43: m43 - other m43; m44: m44 - other m44;
		yourself