Class {
	#name : #WDSShadowSceneRendererViewport,
	#superclass : #WDSAbstractSceneRendererViewport,
	#category : #'WodenEngine-Scene-Rendering'
}

{ #category : #adding }
WDSShadowSceneRendererViewport >> addBackgroundVisibleObject: aNode [
	"Supress background objects from shadow rendering."
]

{ #category : #adding }
WDSShadowSceneRendererViewport >> addForegroundVisibleObject: aNode [
	"Supress foreground objects from shadow rendering."
]
