special matrices
ones
	^ self new
		m11: 1.0 asNativeDouble; m12: 1.0 asNativeDouble; m13: 1.0 asNativeDouble; m14: 1.0 asNativeDouble;
		m21: 1.0 asNativeDouble; m22: 1.0 asNativeDouble; m23: 1.0 asNativeDouble; m24: 1.0 asNativeDouble;
		m31: 1.0 asNativeDouble; m32: 1.0 asNativeDouble; m33: 1.0 asNativeDouble; m34: 1.0 asNativeDouble;
		m41: 1.0 asNativeDouble; m42: 1.0 asNativeDouble; m43: 1.0 asNativeDouble; m44: 1.0 asNativeDouble;
		yourself