special matrices
ones
	^ self new
		m11: 1.0 asNativeFloat; m12: 1.0 asNativeFloat; m13: 1.0 asNativeFloat; m14: 1.0 asNativeFloat;
		m21: 1.0 asNativeFloat; m22: 1.0 asNativeFloat; m23: 1.0 asNativeFloat; m24: 1.0 asNativeFloat;
		m31: 1.0 asNativeFloat; m32: 1.0 asNativeFloat; m33: 1.0 asNativeFloat; m34: 1.0 asNativeFloat;
		m41: 1.0 asNativeFloat; m42: 1.0 asNativeFloat; m43: 1.0 asNativeFloat; m44: 1.0 asNativeFloat;
		yourself